---
- name: Crear el grupo
  group:
    name:  "{{ group_name }}"
    state: present
    
- name: Verificar la creación del grupo
  command: getent group "{{ group_name }}"
  register: result
  changed_when: false
  
- name: Mostrar el resultado
  debug:
    var: result.stdout_lines
